'use strict';
const $=id=>document.getElementById(id),{CopyDocument,tokens}=CopyCore,{fingerprint,savePng:saveFile}=PixelCore;
let doc=new CopyDocument(window.BEAD_COPY_CHINESE,window.BEAD_COPY_CATALOG),selected='',directory=null,handle=null,hash='',fileName='zh.json',busy=false;
const groups={mod:'系统提示',bench:'拼豆台',editor:'拼豆编辑',library:'图纸库',manufacturing:'制作与消耗',processing:'原料加工',product:'成品名称',material:'材料',color:'颜色',weapon:'武器',effect:'宝石特效',refinement:'精炼',soul:'强化',import:'导入',debug:'调试提示',config:'设置',creative:'创造模式',art:'美术',palette:'拼豆染色',WorkshopProgress:'故事与委托',WorkshopGuidance:'故事与委托',WorkshopService:'故事与委托',ReferencePatterns:'参考图纸',PatternDetailMenu:'图纸详情',WorkshopMenu:'工坊界面',EditorPanel:'拼豆编辑',PalettePanel:'拼豆染色'};
function category(key){return groups[key.startsWith('copy.')?key.split('.')[1]:key.split('.')[0]]||'其他界面与提示';}
function message(text,error=false){$('status').textContent=text;$('status').classList.toggle('error',error);}
function update(){let issues=doc.issues(),changed=doc.changed.length;$('connect').disabled=$('locale').disabled=busy;$('value').disabled=busy||!directory;$('save').disabled=busy||!directory||!changed||issues.length>0;$('reset').disabled=busy||!directory||!selected||doc.values[selected]===doc.saved[selected];$('dirty').textContent=!directory?'浏览模式':changed?changed+' 项未保存':'已保存';$('dirty').classList.toggle('changed',!!changed);$('problems').textContent=issues.length?issues.length+' 项文案格式需要修正后才能保存（左侧红框标记）。':'';document.title=(changed?'● ':'')+'拼豆文案工坊';}
function renderList(){let q=$('search').value.toLowerCase(),group=$('category').value,only=$('onlyChanged').checked,oldScroll=$('entries').scrollTop;const issues=new Set(doc.issues().map(i=>i.key));let keys=Object.keys(doc.values).filter(k=>(group==='all'||category(k)===group)&&(!only||doc.values[k]!==doc.saved[k])&&(k+' '+doc.values[k]+' '+doc.saved[k]).toLowerCase().includes(q));$('count').textContent=keys.length+' 条';$('entries').replaceChildren(...keys.map(key=>{let b=document.createElement('button');b.className='entry'+(key===selected?' active':'')+(doc.values[key]!==doc.saved[key]?' changed':'')+(issues.has(key)?' invalid':'');b.title=key;let t=document.createElement('strong'),k=document.createElement('small');t.textContent=doc.values[key]||'（空文案）';k.textContent=category(key)+' · '+key;t.textContent=t.textContent.replaceAll('\n',' ');b.append(t,k);b.onclick=()=>{if(!busy)select(key);};return b;}));$('entries').scrollTop=oldScroll;}
function details(){if(!selected)return;let value=doc.values[selected];$('validation').textContent=doc.issues().find(i=>i.key===selected)?.error||'';$('length').textContent=value.length+' 字符';$('previewText').textContent=value.replaceAll('^^','\n\n').replaceAll('[#]','\n标题：');$('original').textContent=doc.saved[selected];let required=[];try{required=tokens(selected,doc.contracts[selected]);}catch{}$('tokens').replaceChildren(...required.map(t=>{let code=document.createElement('code');code.textContent=t;return code;}));if(!required.length)$('tokens').textContent='本项没有动态占位符。';update();}
function select(key){selected=key;$('title').textContent=category(key);$('key').value=key;$('value').value=doc.values[key];details();renderList();}
function categories(){const previous=$('category').value,names=[...new Set(Object.keys(doc.values).map(category))].sort();$('category').replaceChildren(...['all',...names].map(n=>{let o=document.createElement('option');o.value=n;o.textContent=n==='all'?'全部分类':n;return o;}));$('category').value=names.includes(previous)?previous:'all';}
async function leave(){if(!doc.dirty)return true;return new Promise(resolve=>{let dialog=$('leaveDialog');const finish=v=>{dialog.close();resolve(v);};dialog.oncancel=e=>{e.preventDefault();finish(false);};$('cancelLeave').onclick=()=>finish(false);$('discardLeave').onclick=()=>finish(true);$('saveLeave').onclick=async()=>{dialog.close();resolve(await save());};dialog.showModal();});}
async function locate(root){for(let parts of [['BetterBeads','i18n'],['i18n'],[]])try{let d=root;for(let p of parts)d=await d.getDirectoryHandle(p);await d.getFileHandle($('locale').value);return d;}catch{}throw Error('没有找到所选JSON。请选择项目、BetterBeads或i18n文件夹。');}
async function read(dir,name){let nextHandle=await dir.getFileHandle(name),file=await nextHandle.getFile(),bytes=await file.arrayBuffer();let next=new CopyDocument(JSON.parse(new TextDecoder().decode(bytes).replace(/^\uFEFF/,'')),window.BEAD_COPY_CATALOG);let nextHash=await fingerprint(bytes);doc=next;directory=dir;handle=nextHandle;hash=nextHash;fileName=name;$('locale').value=name;$('connection').textContent='已连接：'+dir.name+' / '+name;$('filePath').textContent='i18n/'+name;categories();select(Object.hasOwn(doc.values,selected)?selected:Object.keys(doc.values)[0]);}
async function connect(){if(busy)return;if(!window.showDirectoryPicker){message('请使用桌面版Edge或Chrome打开此页面，以便直接写入文件。',true);return;}if(!await leave())return;try{let root=await window.showDirectoryPicker({id:'betterbeads-copy-editor',mode:'readwrite'});busy=true;update();let dir=await locate(root);await read(dir,$('locale').value);$('connection').textContent='已连接：'+root.name+' → i18n/'+fileName;message('已打开 '+fileName+'，保存将直接修改该文件。');}catch(e){if(e.name!=='AbortError')message('无法打开：'+e.message,true);}finally{busy=false;update();}}
async function save(){if(busy)return false;if(!doc.dirty)return true;if(!directory)return false;busy=true;update();try{const bytes=new TextEncoder().encode(doc.serialize()),backup=await directory.getDirectoryHandle('.text-backups',{create:true});const name=fileName+'.'+new Date().toISOString().replaceAll(':','-')+'.'+crypto.randomUUID().slice(0,8)+'.bak';hash=await saveFile(handle,backup,name,hash,bytes);const changed=doc.changed.length;doc.markSaved();message('已保存 '+changed+' 项到 i18n/'+fileName+'，旧文件已备份；重启游戏生效。');details();renderList();return true;}catch(e){message('保存未完成：'+e.message,true);return false;}finally{busy=false;update();}}
$('connect').onclick=connect;$('save').onclick=save;$('search').oninput=$('category').onchange=$('onlyChanged').onchange=renderList;
$('value').oninput=()=>{if(busy||!directory)return;doc.set(selected,$('value').value);details();renderList();};$('reset').onclick=()=>{if(!busy&&directory){doc.reset(selected);select(selected);}};
$('locale').onchange=async()=>{let name=$('locale').value;if(!directory){fileName=name;doc=new CopyDocument(name==='zh.json'?window.BEAD_COPY_CHINESE:window.BEAD_COPY_CATALOG,window.BEAD_COPY_CATALOG);categories();select(Object.hasOwn(doc.values,selected)?selected:Object.keys(doc.values)[0]);return;}if(!await leave()){$('locale').value=fileName;return;}busy=true;update();try{await read(directory,name);message('已切换至 '+name+'。');}catch(e){$('locale').value=fileName;message('切换失败：'+e.message,true);}finally{busy=false;update();}};
window.addEventListener('beforeunload',e=>{if(doc.dirty||busy){e.preventDefault();e.returnValue='';}});
window.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();if(!busy&&!$('leaveDialog').open)save();}});
if(!window.showDirectoryPicker)$('support').textContent='直接保存需要桌面版Edge / Chrome';
categories();select(Object.keys(doc.values).find(k=>k.startsWith('copy.ReferencePatterns.'))||Object.keys(doc.values)[0]);

$('reload').onclick=async()=>{if(busy||!directory||!await leave())return;busy=true;update();try{await read(directory,fileName);message('已重新载入磁盘文案。');}catch(e){message(e.message,true);}finally{busy=false;update();}};
