import fs from 'node:fs';import path from 'node:path';import zlib from 'node:zlib';import vm from 'node:vm';import assert from 'node:assert/strict';import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),assets=path.join(root,'BetterBeads/assets');
function png(name){const bytes=fs.readFileSync(path.join(assets,name+'.png'));assert.equal(bytes.subarray(0,8).toString('hex'),'89504e470d0a1a0a');let width=bytes.readUInt32BE(16),height=bytes.readUInt32BE(20),idat=[];assert.equal(bytes[24],8);assert.equal(bytes[25],6);for(let i=8;i<bytes.length;){let n=bytes.readUInt32BE(i),type=bytes.subarray(i+4,i+8).toString();if(type==='IDAT')idat.push(bytes.subarray(i+8,i+8+n));i+=n+12;}const raw=zlib.inflateSync(Buffer.concat(idat));assert.equal(raw.length,(width*4+1)*height);for(let y=0;y<height;y++)assert.equal(raw[y*(width*4+1)],0);return{width,height,pixel(x,y){return raw.subarray(y*(width*4+1)+1+x*4,y*(width*4+1)+5+x*4)}};}
const sizes={Board:[24,24],Workbench:[16,32],Beads:[128,64],Ui:[240,24],Icons:[192,32],Status:[96,12],BeadMask:[8,8],ScrollTrack:[8,8],ScrollThumb:[8,16],'Products/Hat':[20,80]};for(let s of ['Picture','WoodOrnament','StoneStatue','Sword','Dagger','Hammer'])sizes['Products/'+s]=[16,16];
for(const [name,size]of Object.entries(sizes)){const p=png(name);assert.deepEqual([p.width,p.height],size,name);assert.equal(p.pixel(0,0)[3],0,`${name}: transparent outer corner`);}
const art=JSON.parse(fs.readFileSync(path.join(assets,'art.json'))),src=JSON.parse(fs.readFileSync(path.join(root,'art/source.json'))),beads=png('Beads');
assert.equal(Object.keys(src.sprites).length,82);assert.equal(Object.keys(art.Beads).length,28);assert.equal(Object.keys(art.Ui).length,10);assert.equal(Object.keys(art.Icons).length,24);assert.equal(Object.keys(art.Status).length,8);
for(const [id,i]of Object.entries(art.Beads)){assert.ok(src.sprites['bead/'+id]);assert.equal(beads.pixel(i%8*16+7,Math.floor(i/8)*16+7)[3],0,id+' center hole');if(id.startsWith('refined-')){let base=art.Beads[id.slice(8)];assert.notDeepEqual(beads.pixel(i%8*16+12,Math.floor(i/8)*16+2),beads.pixel(base%8*16+12,Math.floor(base/8)*16+2),id+' sparkle');}}
const lum=c=>{const v=[0,2,4].map(i=>parseInt(c.slice(i,i+2),16)/255).map(n=>n<=.04045?n/12.92:((n+.055)/1.055)**2.4);return v[0]*.2126+v[1]*.7152+v[2]*.0722;};
const ratio=(a,b)=>(Math.max(lum(a),lum(b))+.05)/(Math.min(lum(a),lum(b))+.05);
assert.ok(ratio(art.Ink,'FFF5DF')>7);assert.ok(ratio(art.Ink,'D9E5C7')>7);assert.ok(ratio(art.MutedInk,'D8CFC0')>4.5);
const html=fs.readFileSync(path.join(root,'art/source-editor.html'),'utf8');for(const m of html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g))new vm.Script(m[1]);
const ids=new Set([...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]));for(const m of html.matchAll(/\$\('([^']+)'\)/g))assert.ok(ids.has(m[1]),'editor element '+m[1]);
const context={window:{}};vm.runInNewContext(fs.readFileSync(path.join(root,'art/source-data.js'),'utf8'),context);assert.equal(JSON.stringify(context.window.BEAD_ART_SOURCE),JSON.stringify(src));
console.log(`PASS 16 PNG sizes and alpha; 82 source sprites; 28 bead mappings and holes; 11 refinement badges; 10 UI states; editor syntax/element bindings/source roundtrip.`);
console.log(`PASS text contrast: normal ${ratio(art.Ink,'FFF5DF').toFixed(2)}:1, selected ${ratio(art.Ink,'D9E5C7').toFixed(2)}:1, disabled ${ratio(art.MutedInk,'D8CFC0').toFixed(2)}:1. Not a browser or in-game visual test.`);
